import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";

/** font family for next js
 * NOTE: avoid using import fonts as on slow net it might show fallback font.
 */
const font = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
